/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error": "#ff716c",
        "on-secondary-fixed": "#40009b",
        "on-primary": "#002c66",
        "tertiary-dim": "#58e7ab",
        "surface-variant": "rgb(var(--surface-variant) / <alpha-value>)",
        "inverse-surface": "#f9f9ff",
        "primary-dim": "#699cff",
        "on-surface": "rgb(var(--on-surface) / <alpha-value>)",
        "on-surface-variant": "rgb(var(--on-surface-variant) / <alpha-value>)",
        "on-error-container": "#ffa8a3",
        "on-primary-fixed": "#000000",
        "secondary": "#ac8aff",
        "on-primary-fixed-variant": "#002a62",
        "on-tertiary-fixed-variant": "#006544",
        "on-tertiary-fixed": "#00452d",
        "primary": "#85adff",
        "tertiary": "#9bffce",
        "on-secondary-fixed-variant": "#5f28c8",
        "error-container": "#9f0519",
        "background": "rgb(var(--background) / <alpha-value>)",
        "inverse-primary": "#005bc4",
        "error-dim": "#d7383b",
        "secondary-dim": "#8455ef",
        "surface-tint": "#85adff",
        "on-tertiary-container": "#005a3c",
        "secondary-fixed-dim": "#ceb9ff",
        "primary-container": "#6e9fff",
        "on-secondary": "#280067",
        "surface-bright": "rgb(var(--surface-container-high) / <alpha-value>)",
        "outline-variant": "rgb(var(--outline-variant) / <alpha-value>)",
        "on-error": "#490006",
        "surface-container-highest": "rgb(var(--surface-container-highest) / <alpha-value>)",
        "surface-container": "rgb(var(--surface-container) / <alpha-value>)",
        "tertiary-fixed-dim": "#58e7ab",
        "on-primary-container": "#002150",
        "tertiary-container": "#69f6b8",
        "secondary-fixed": "#dac9ff",
        "surface-container-lowest": "rgb(var(--surface-container-lowest) / <alpha-value>)",
        "outline": "rgb(var(--outline) / <alpha-value>)",
        "surface-container-low": "rgb(var(--surface-container-low) / <alpha-value>)",
        "on-background": "rgb(var(--on-surface) / <alpha-value>)",
        "secondary-container": "#5516be",
        "surface-dim": "rgb(var(--background) / <alpha-value>)",
        "primary-fixed-dim": "#5391ff",
        "surface-container-high": "rgb(var(--surface-container-high) / <alpha-value>)",
        "on-secondary-container": "#d9c8ff",
        "primary-fixed": "#6e9fff",
        "on-tertiary": "#006443",
        "inverse-on-surface": "#52555c",
        "surface": "rgb(var(--background) / <alpha-value>)",
        "tertiary-fixed": "#69f6b8"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      backgroundImage: {
        'glass-gradient': 'linear-gradient(rgba(22, 26, 33, 0.7), rgba(22, 26, 33, 0.7))',
      }
    },
  },
  plugins: [],
}
